### ISSUE TITLE
Build failure. SymbolTable has no member resolve

### ISSUE THREAD

**Issue by swang206** [GrammaTech/ddisasm#33] opened 2021-07-27 15:59 UTC
/usr/local/include/souffle/SymbolTable.h:40:7: error: use of deleted function 'souffle::Lock::Lock(const souffle::Lock&)'
In file included from /usr/local/include/souffle/SymbolTable.h:21,
                 from /usr/local/include/souffle/SouffleInterface.h:21,
                 from /usr/local/include/souffle/CompiledSouffle.h:22,
                 from /home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.h:26,
                 from /home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.cpp:23:
/usr/local/include/souffle/utility/ParallelUtil.h:110:7: note: 'souffle::Lock::Lock(const souffle::Lock&)' is implicitly deleted because the default definition would be ill-formed:
  110 | class Lock {
      |       ^~~~
/usr/local/include/souffle/utility/ParallelUtil.h:110:7: error: use of deleted function 'std::mutex::mutex(const std::mutex&)'
In file included from /usr/local/include/c++/12.0.0/mutex:43,
                 from /usr/local/include/souffle/SignalHandler.h:26,
                 from /usr/local/include/souffle/CompiledSouffle.h:21,
                 from /home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.h:26,
                 from /home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.cpp:23:
/usr/local/include/c++/12.0.0/bits/std_mutex.h:94:5: note: declared here
   94 |     mutex(const mutex&) = delete;
      |     ^~~~~
/home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.cpp:65:43: error: 'class souffle::SymbolTable' has no member named 'resolve'
   65 |                     Stream << SymbolTable.resolve(Tuple[I]);
      |                                           ^~~~~~~

**Comment by kwarrick** [comment] 2021-07-30 08:50
Most likely, this is caused by compiling against the master branch of Souffle, which is not stable.

Ddisasm uses the latest release version of Souffle (2.0.2). 

I usually build Souffle like this:
```
$ git clone -b 2.0.2 https://github.com/souffle-lang/souffle
$ cd souffle sh ./bootstrap
$ ./configure --prefix=/usr --enable-64bit-domain
$ make -j4 install
```

**Comment by eschulte** [comment] 2021-08-04 16:14
I'm closing this for now.  Please re-open if kwarrick's suggestion above doesn't resolve your issue.

**Closed by eschulte** 2021-08-04 16:14 UTC
Labels: binary fails
